// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, unused_import, unnecessary_import
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import'firebase_options.dart';
import'package:firebase_core/firebase_core.dart';

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH69otI7Rhh6VfAVaZYrOw_tAWOVMX8MY',
    appId: '1:485397222127:web:ab21c6baf4e18a6bb6811a',
    messagingSenderId: '485397222127',
    projectId: 'my-app-skin-disease-diagnose',
    authDomain: 'my-app-skin-disease-diagnose.firebaseapp.com',
    storageBucket: 'my-app-skin-disease-diagnose.firebasestorage.app',
    measurementId: 'G-6TKFPKGFRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVCmv2j_TKDp4mJ1PANFko87v1xlRNaG0',
    appId: '1:485397222127:android:9ac49708a8d53f62b6811a',
    messagingSenderId: '485397222127',
    projectId: 'my-app-skin-disease-diagnose',
    storageBucket: 'my-app-skin-disease-diagnose.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBH69otI7Rhh6VfAVaZYrOw_tAWOVMX8MY',
    appId: '1:485397222127:web:d388904deb0e5624b6811a',
    messagingSenderId: '485397222127',
    projectId: 'my-app-skin-disease-diagnose',
    authDomain: 'my-app-skin-disease-diagnose.firebaseapp.com',
    storageBucket: 'my-app-skin-disease-diagnose.firebasestorage.app',
    measurementId: 'G-QYG75HW223',
  );
}
